name: Java CI (no Maven)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Criar pasta de build
        run: mkdir -p out

      - name: Compilar projeto Java
        run: |
          find . -name "*.java" > sources.txt
          javac -d out @sources.txt

      - name: Upload artefatos compilados
        uses: actions/upload-artifact@v4
        with:
          name: lavajato-classes
          path: out
